# Generated by Django 5.1.1 on 2024-09-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=90, null=True)),
                ('Mobile', models.CharField(max_length=60, null=True)),
                ('Subject', models.CharField(max_length=200, null=True)),
                ('Message', models.TextField(null=True)),
            ],
        ),
    ]
