# Generated by Django 5.1.1 on 2024-09-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('student_picture', models.ImageField(null=True, upload_to='static/placement/')),
                ('company_name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/faculty/')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('experience', models.CharField(max_length=20, null=True)),
                ('specialization', models.CharField(max_length=30, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('qualification', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('feedback', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/picture/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_picture', models.ImageField(null=True, upload_to='static/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_infra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('pictur', models.ImageField(null=True, upload_to='static/infra/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField(null=True)),
                ('notice_link', models.CharField(max_length=50, null=True)),
                ('posted_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(null=True, upload_to='static/recruiter/')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('slider_image', models.ImageField(null=True, upload_to='static/slider/')),
            ],
        ),
    ]
