# Generated by Django 5.1.1 on 2024-09-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tbl_alumni_tbl_faculty_tbl_feedback_tbl_gallery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_infra',
            old_name='pictur',
            new_name='picture',
        ),
    ]
