# Generated by Django 5.1.1 on 2024-09-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_experience_tbl_faculty_experiance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=60, null=True)),
                ('seat', models.CharField(max_length=30, null=True)),
                ('course_code', models.CharField(max_length=20, null=True)),
                ('duration', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
