# Generated by Django 5.1.1 on 2024-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_tbl_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_courses',
            old_name='seat',
            new_name='seats',
        ),
        migrations.AddField(
            model_name='tbl_alumni',
            name='placement_session',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
