# Generated by Django 5.1.1 on 2024-09-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_seat_tbl_courses_seats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_feedback',
            old_name='feedback',
            new_name='message',
        ),
    ]
