# Generated by Django 5.1.1 on 2024-09-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_feedback_tbl_feedback_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_feedback',
            old_name='message',
            new_name='feedback',
        ),
    ]
